export enum ActionTypes {
  FETCH_USER,
  FETCH_CATEGORIES,
  IS_POSTING,
  GET_NEW_ARTICLE,
  RESET_NEW_ARTICLE,
  DISPLAY_MODAL,
  REMOVE_MODAL,
  LOADING_ARTICLES,
  FETCH_ARTICLES_BY_CATEGORY,
  RESET_ARTICLES_STATE,
  HANDLE_LIKE,
  RECEIVE_USER_POSTS,
  RECEIVE_POSTS_BY_KEYWORD
}

export const FETCH_USER = "FETCH_USER";

export const LOADING_ARTICLES = "LOADING_ARTICLES";
export const FETCH_ARTICLES_BY_CATEGORY = "FETCH_ARTICLES_BY_CATEGORY";

export const HANDLE_LIKE = "HANDLE_LIKE";

export const RECEIVE_USER_POSTS = "RECEIVE_USER_POSTS";

export const RECEIVE_POSTS_BY_KEYWORD = "RECEIVE_POSTS_BY_KEYWORD";
