export enum ActionTypes {
  FETCH_USER,
  FETCH_CATEGORIES,
  IS_POSTING,
  GET_NEW_ARTICLE,
  RESET_NEW_ARTICLE,
  DISPLAY_MODAL,
  REMOVE_MODAL,
  LOADING_ARTICLES,
  FETCH_ARTICLES_BY_CATEGORY,
  RESET_ARTICLES_STATE,
  HANDLE_LIKE,
  RECEIVE_USER_POSTS,
  RECEIVE_POSTS_BY_KEYWORD
}

export const FETCH_USER = "FETCH_USER";
export const FETCH_CATEGORIES = "GET_CATEGORIES";

export const IS_POSTING = "IS_POSTING";
export const RECEIVE_NEW_ARTICLE = "RECEIVE_NEW_ARTICLE";
export const RESET_NEW_ARTICLE = "RESET_NEW_ARTICLE";

export const DISPLAY_MODAL = "DISPLAY_MODAL";
export const REMOVE_MODAL = "REMOVE_MODAL";

export const LOADING_ARTICLES = "LOADING_ARTICLES";
export const FETCH_ARTICLES_BY_CATEGORY = "FETCH_ARTICLES_BY_CATEGORY";
export const RESET_ARTICLES_STATE = "RESET_ARTICLES_STATE";

export const HANDLE_LIKE = "HANDLE_LIKE";

export const RECEIVE_USER_POSTS = "RECEIVE_USER_POSTS";

export const RECEIVE_POSTS_BY_KEYWORD = "RECEIVE_POSTS_BY_KEYWORD";
